#!/bin/bash

# SET YOUR DIRECTORY PATH
KALIPYFI_DIR="/home/kali/kalipyfi/"
echo
echo "launching kalipyfi from wrapper"
# leave these be
source "$KALIPYFI_DIR/.venv/bin/activate"
"$KALIPYFI_DIR/.venv/bin/python3" "$KALIPYFI_DIR/kalipyfi.py" "$@"
