#!/bin/bash

# SET YOUR DIRECTORY PATH
KALIPYFI_DIR="/home/flip/tmuxp-kalipifi/"

# leave these
source "$KALIPYFI_DIR/.venv/bin/activate"
"$KALIPYFI_DIR/.venv/bin/python3" "$KALIPYFI_DIR/kalipyfi.py" "$@"
