interfaces:
  wlan:
  - description: hotspot
    locked: true
    name: wlx9cefd5f93a81
  - description: monitor
    locked: false
    name: wlan1
  - description: monitor
    locked: false
    name: wlan2
  - description: client
    locked: true
    name: wlan3
