interfaces:
  wlan:
  - description: ethernet
    locked: false
    name: eth0
  - description: hotspot
    locked: true
    name: wlan0
  - description: monitor
    locked: false
    name: wlan1
  - description: monitor
    locked: false
    name: wlan2
  - description: client
    locked: true
    name: wlan3
presets:
  1:
    description: db_networks
    options:
      -sn: true
      -T4: true

  2:
    description: db_hosts
    options:
      -A: true
      -T4: true
      --top-ports: 1000
