interfaces:
  wlan:
  - description: ethernet
    locked: false
    name: ens33
  - description: hotspot
    locked: true
    name: wlan0
  - description: monitor
    locked: false
    name: wlan1
  - description: monitor
    locked: false
    name: wlan2
  - description: client
    locked: true
    name: wlan3
presets:
  1:
    description: check-hosts
    options:
      -sn: true
      -T4: true

  2:
    description: top1000-services
    options:
      -A: true
      -T4: true
      --top-ports: 1000
