interfaces:
  wlan:
  - description: hotspot
    locked: true
    name: wlan0
  - description: monitor
    locked: false
    name: wlan1
  - description: monitor
    locked: false
    name: wlan2
  - description: client
    locked: true
    name: wlan3
  - description: monitor
    locked: false
    name: wlan4
presets:
  1:
    description: sVC
    options:
      sVC: true
      --top-ports: true