user:
  wpasec-key:

interfaces:
  wlan:
    - name: wlan0
      description: "hotspot"
      locked: True
    - name: wlan1
      description: "monitor"
      locked: False
    - name: wlan2
      description: "monitor"
      locked: False
    - name: wlan3
      description: "client"
      locked: False

presets:
  1:
    description: "aggressive"
    autobpf: True
    options:
      "--gpsd": True
      "-A": True
      "-F": True

  2:
    description: "passive"
    autobpf: True
    options:
      "--gpsd": True
      "--attemptapmax": 0
      "-F": True

  3:
    description: "rca a"
    autobpf: True
    options:
      "--gpsd": True
      "--rcascan": a
      "-A": True
      "-F": True

  4:
    description: "rca p"
    autobpf: true
    options:
      "--gpsd": true
      "--rcascan": p
      "-F": true
      "-A": true

  5:
    description: "auto iface essid"
    autobpf: true
    options:
      "--gpsd": true
      "--essidlist": default
      "-A": true
      "-F": true


