user:
  wpasec-key:

interfaces:
  wlan:
    - name: wlan0
      description: "hotspot"
      locked: True
    - name: wlan1
      description: "monitor"
      locked: False
    - name: wlan2
      description: "monitor"
      locked: False
    - name: wlan3
      description: "client"
      locked: False

presets:
  1:
    description: "aggressive"
    options:
      "autobpf": True
      "--gpsd": True
      "-A": True
      "-F": True

  2:
    description: "passive"
    options:
      "autobpf": True
      "--gpsd": True
      "--attemptapmax": 0
      "-F": True

  3:
    description: "silent"
    options:
      "--gpsd": True
      "--attemptapmax": 0
      "--disable_beacon": True
      "-F": True

  4:
    description: "rca a"
    options:
      "autobpf": True
      "--gpsd": True
      "--rcascan": a
      "-A": True
      "-F": True

  5:
    description: "rca p"
    options:
      "autobpf": True
      "--gpsd": True
      "--rcascan": p
      "-F": True
      "-A": True

