interfaces:
  wlan:
  - description: hotspot
    locked: true
    name: wlan0
  - description: monitor
    locked: false
    name: wlan1
  - description: monitor
    locked: false
    name: wlan2
  - description: client
    locked: true
    name: wlan3

presets:
  1:
    description: lead
    options:
      --gpsd: true
      -A: true
      -F: true
      autobpf: true
  2:
    description: follow
    options:
      -A: true
      -F: true
      autobpf: true
  3:
    description: passive
    options:
      --attemptapmax: 0
      --gpsd: true
      -F: true
      autobpf: true
  4:
    description: silent
    options:
      --attemptapmax: 0
      --disable_beacon: true
      --gpsd: true
      -F: true
      autobpf: true
  5:
    description: rca a
    options:
      --rcascan: a
      -A: true
      -F: true
      autobpf: true
  6:
    description: rca p
    options:
      --rcascan: p
      -A: true
      -F: true
      autobpf: true
wpa-sec:
  api_key: