interfaces:
  wlan:
  - description: monitor
    locked: false
    name: wlan1
presets:
  1:
    description: aggressive
    options:
      -A: true
      -F: true
  2:
    description: passive
    options:
      --attemptapmax: 0
      -F: true
  3:
    description: silent
    options:
      --attemptapmax: 0
      --disable_beacon: true
      -F: true
  4:
    description: rca a
    options:
      --rcascan: a
      -A: true
      -F: true
  5:
    description: rca p
    options:
      --rcascan: p
      -A: true
      -F: true
wpa-sec:
  api_key:
